name: pack-source-code

on:
  push:
    tags:
      - '**'

jobs:
  source-pack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: preparing-environment
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential python

      - name: packing-source-code
        run: |
          make distribute

      - name: prerelease-with-packed-source-code
        uses: softprops/action-gh-release@v2
        with:
          files: dist/supertuple.hpp
          draft: true
