name: run-tests-ci

on: [push, pull_request]

jobs:
  test-runner:
    strategy:
      matrix:
        compiler: [g++, clang++]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jwlawson/actions-setup-cmake@v1

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential clang cmake ninja-build

      - name: Configure project with CMake
        run: |
          cmake -S . -B build \
            -DCMAKE_CXX_COMPILER=${{  matrix.compiler }} \
            -DBUILD_TESTING=ON                           \
            -G Ninja

      - name: Build project
        run: cmake --build build

      - name: Run tests
        run: ctest --test-dir build --output-on-failure
